#+title: Problem Description
#+author: Arun Khattri

* Problem Description
Goal is to predict how likely individuals are to receive their H1N1 and seasonal flu vaccines.
Specifically, we'll be predicting two probabilities:
+ one for h1n1_vaccine, and
+ one for seasonal_vaccine.

Each row in the dataset represents one person who responded to the National 2009 H1N1 Flu Survey.

* Labels
Two target variables:

+ =h1n1_vaccine= - Whether respondent received H1N1 flu vaccine.
+ =seasonal_vaccine= - Whether respondent received seasonal flu vaccine.

Both are binary variables: =0= = No; =1= = Yes. Some respondents didn't get either vaccine, others got only one, and some got both. This is formulated as a multilabel (and /not/ multiclass) problem.

* Features in the dataset
Data-set[fn:1] has *36* columns. The first column =respondent_id= is a unique and random identifier. Remaining 35 features are described below.

1. =h1n1_concern=: Level of concern about the H1N1 flu.
   + =0=: Not at all concerned; =1=: Not very concerned; =2=: Somewhat concerned; =3=: Very concerned.
2. =h1n1_knowledge=: Level of knowledge about H1N1 flu.
   + =0=: No knowledge; =1=: A little knowledge; =2=: A lot of knowledge.
3. =behavioral_antiviral_meds=: Has taken antiviral medications.(/binary/)
4. =behavioral_avoidance=: has avoided close contact with others with flu-like symptoms.(/binary/)
5. =behavioral_face_mask=: Has bought a face mask.(/binary/)
6. =behavioral_wash_hand=: has frequently washed hands or used hand sanitizer.(/binary/)
7. =behavioral_large_gatherings=: Has reduced time at large gatherings.(/binary/)
8. =behavioral_outside_home=: Has reduced contact with people outside of own household.(/binary/)
9. =behavioral_touch_face= - Has avoided touching eyes, nose, or mouth. (/binary/) doctor_recc_h1n1 - H1N1 flu vaccine was recommended by doctor. (binary)
10. =doctor_recc_h1n1= - H1N1 flu vaccine was recommended by doctor. (/binary/)
11. =doctor_recc_seasonal= - Seasonal flu vaccine was recommended by doctor. (/binary/)
12. =chronic_med_condition= - Has any of the following chronic medical conditions: asthma or an other lung condition, diabetes, a heart condition, a kidney condition, sickle cell anemia or other anemia, a neurological or neuromuscular condition, a liver condition, or a weakened immune system caused by a chronic illness or by medicines taken for a chronic illness. (/binary/)
13. =child_under_6_months= - Has regular close contact with a child under the age of six months. (/binary/)
14. =health_worker= - Is a healthcare worker. (/binary/)
15. =health_insurance= - Has health insurance. (/binary/)
16. =opinion_h1n1_vacc_effective= - Respondent's opinion about H1N1 vaccine effectiveness.
    + =1= : Not at all effective; =2= : Not very effective; =3= : Don't know; =4= : Somewhat effective; =5= : Very effective.
17. =opinion_h1n1_risk= - Respondent's opinion about risk of getting sick with H1N1 flu without vaccine.
    + =1= : Very Low; =2= : Somewhat low; =3= : Don't know; =4= : Somewhat high; =5= : Very high.
18. =opinion_h1n1_sick_from_vacc= - Respondent's worry of getting sick from taking H1N1 vaccine.
    + =1= : Not at all worried; =2= : Not very worried; =3= : Don't know; =4= : Somewhat worried; =5= : Very worried.
19. =opinion_seas_vacc_effective= - Respondent's opinion about seasonal flu vaccine effectiveness.
    + =1= : Not at all effective; =2= : Not very effective; =3= : Don't know; =4= : Somewhat effective; =5= : Very effective.
20. =opinion_seas_risk= - Respondent's opinion about risk of getting sick with seasonal flu without vaccine.
    + 1 = Very Low; 2 = Somewhat low; 3 = Don't know; 4 = Somewhat high; 5 = Very high.
21. =opinion_seas_sick_from_vacc= - Respondent's worry of getting sick from taking seasonal flu vaccine.
    + =1= : Not at all worried; =2= : Not very worried; =3= : Don't know; =4= : Somewhat worried; =5= : Very worried.
22. =age_group= - Age group of respondent.
23. =education= - Self-reported education level.
24. =race= - Race of respondent.
25. =sex= - Sex of respondent.
26. =income_poverty= - Household annual income of respondent with respect to 2008 Census poverty thresholds.
27. =marital_status= - Marital status of respondent.
28. =rent_or_own= - Housing situation of respondent.
29. =employment_status= - Employment status of respondent.
30. =hhs_geo_region= - Respondent's residence using a 10-region geographic classification defined by the U.S. Dept. of Health and Human Services. Values are represented as short random character strings.
31. =census_msa= - Respondent's residence within metropolitan statistical areas (MSA) as defined by the U.S. Census.
32. =household_adults= - Number of other adults in household, top-coded to 3.
33. =household_children= - Number of children in household, top-coded to 3.
34. =employment_industry= - Type of industry respondent is employed in. Values are represented as short random character strings.
35. =employment_occupation= - Type of occupation of respondent. Values are represented as short random character strings.

* Performance metric
Performance will be evaluated according to the area under the receiver operating characteristic curve (ROC AUC) for each of the two target variables. The mean of these two scores will be the overall score. A higher value indicates stronger performance.

In Python, we can calculate this using =sklearn.metrics.roc_auc_score= for this multilabel setup with the default =average​=="macro"= parameter.

* Footnotes

[fn:1] DrivenData. (2020). [[https://www.drivendata.org/competitions/66/flu-shot-learning][Flu Shot Learning]]: Predict H1N1 and Seasonal Flu Vaccines. Retrieved [Jan 20, 2024].
